services:
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PG_HOST: postgres
      PG_PORT: "5432"
      PG_USER: /run/secrets/postgres_user
      PG_PASSWORD: /run/secrets/postgres_password
      PG_DBNAME: "users"
      PG_SSL_MODE: "disable"
      PG_TIMEZONE: "UTC"
      PG_CONNECT_TIMEOUT: "5"
    secrets:
      - postgres_user
      - postgres_password

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  front-end:
    build:
      context: ./../front-end
      dockerfile: ./../front-end/front-end.dockerfile
    ports:
      - "8081:8081"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: http://localhost:8080

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: ./../logger-service/logger-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_USERNAME: /run/secrets/mongo_user
      MONGO_PASSWORD: /run/secrets/mongo_password
    secrets:
      - mongo_user
      - mongo_password

  listener-service:
    build:
      context: ./../listener-service
      dockerfile: ./../listener-service/listener-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  mailer-service:
    build:
      context: ./../mail-service
      dockerfile: ./../mail-service/mail-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_ADDRESS: "john.smith@example.com"
      FROM_NAME: "John Smith"

  mongo:
    image: "mongo:6.0.21"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_user
      - mongo_password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: "postgres:17.4"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: users
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mailhog:
    image: "mailhog/mailhog:latest"
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./db-data/rabbitmq/:/var/lib/rabbitmq/"

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  mongo_user:
    file: ./secrets/mongo_user.txt
  mongo_password:
    file: ./secrets/mongo_password.txt